@apiUrl = http://vm4430.kaj.pouta.csc.fi:8352

POST {{apiUrl}}/bookings
Content-Type: application/json

{
    "guest_id": 1,
    "room_id": 2,
    "datefrom": "2025-05-01",
    "dateto": "2025-05-10"
}